Updating

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,68 +29,51 @@ jobs:
             echo "EXPO_TOKEN length: ${#EXPO_TOKEN}"
           fi
 
-      - name: Debug - Show Firebase Variables  # debug test
-        run: |
-          echo "App ID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}"
-          echo "Project ID: ${{ secrets.FIREBASE_PROJECT_ID }}"
-          echo "FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}"
-          echo "FIREBASE_APP_ID_IOS: ${{ secrets.FIREBASE_APP_ID_IOS }}"
+      - name: Setup EAS
+        uses: expo/expo-github-action@v8
+        with:
+          eas-version: latest
+          token: ${{ secrets.EXPO_TOKEN }}
 
-      - name: FIREBASE_TOKEN is
+      - name: Install Dependencies
+        run: npm ci
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.R_ACCESS_TOKEN }}
+
+      - name: Build Android
+        run: eas build --platform android --profile production --non-interactive
+
+      - name: Get Android Build URL
+        id: get_build_url
         run: |
-          if [ -z "${{ secrets.FIREBASE_TOKEN }}" ]; then
-            echo "FIREBASE_TOKEN is empty"
-          else
-            export FIREBASE_TOKEN="${{ secrets.FIREBASE_TOKEN }}"
-            echo "FIREBASE_TOKEN starts with: ${FIREBASE_TOKEN:0:5}"
-            echo "FIREBASE_TOKEN length: ${#FIREBASE_TOKEN}"
+          BUILD_URL=$(eas build:list --platform android --status finished --non-interactive --json | jq -r '.[0].artifacts.buildUrl')
+          echo "::set-output name=url::$BUILD_URL"
+      
+      - name: Debug EAS Build List (Raw Output) # debug test
+        run: |
+          eas build:list --platform android --status finished
+      
+      - name: Debug EXPO_TOKEN # debug test
+        run: |
+          echo "EXPO_TOKEN Length: ${#EXPO_TOKEN}"
+        env:
+          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
+
+      - name: Download APK from EAS
+        run: |
+          if [[ -z "${{ steps.get_build_url.outputs.url }}" ]]; then
+            echo "Error: No build URL found. Exiting."
+            exit 1
           fi
+          echo "Downloading APK from: ${{ steps.get_build_url.outputs.url }}"
+          mkdir -p builds
+          curl -L -o builds/app-release.apk "${{ steps.get_build_url.outputs.url }}" # -L follows redirects
 
-      # - name: Setup EAS
-      #   uses: expo/expo-github-action@v8
-      #   with:
-      #     eas-version: latest
-      #     token: ${{ secrets.EXPO_TOKEN }}
-
-      # - name: Install Dependencies
-      #   run: npm ci
-      #   env:
-      #     NODE_AUTH_TOKEN: ${{ secrets.R_ACCESS_TOKEN }}
-
-      # - name: Build Android
-      #   run: eas build --platform android --profile production --non-interactive
-
-      # - name: Get Android Build URL
-      #   id: get_build_url
-      #   run: |
-      #     BUILD_URL=$(eas build:list --platform android --status finished --non-interactive --json | jq -r '.[0].artifacts.buildUrl')
-      #     echo "::set-output name=url::$BUILD_URL"
-      
-      # - name: Debug EAS Build List (Raw Output) # debug test
-      #   run: |
-      #     eas build:list --platform android --status finished
-      
-      # - name: Debug EXPO_TOKEN # debug test
-      #   run: |
-      #     echo "EXPO_TOKEN Length: ${#EXPO_TOKEN}"
-      #   env:
-      #     EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
-
-      # - name: Download APK from EAS
-      #   run: |
-      #     if [[ -z "${{ steps.get_build_url.outputs.url }}" ]]; then
-      #       echo "Error: No build URL found. Exiting."
-      #       exit 1
-      #     fi
-      #     echo "Downloading APK from: ${{ steps.get_build_url.outputs.url }}"
-      #     mkdir -p builds
-      #     curl -L -o builds/app-release.apk "${{ steps.get_build_url.outputs.url }}" # -L follows redirects
-
-      # - name: Upload APK as Artifact
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: build-artifacts
-      #     path: builds/app-release.apk
+      - name: Upload APK as Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: build-artifacts
+          path: builds/app-release.apk
 
       # - name: Build iOS App (Simulator)
       #   run: eas build --platform ios --profile production --non-interactive --output builds/
@@ -103,7 +86,29 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: FIREBASE_TOKEN 2 is
+      - name: Download Build Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: build-artifacts
+          path: builds
+
+      - name: Install Firebase CLI
+        run: npm install -g firebase-tools
+
+      - name: Debug - List Files in Builds Folder
+        run: ls -lh builds/
+
+      - name: Debug - List All Files # debug test
+        run: find . -type f
+
+      - name: Debug - Show Firebase Variables # debug test
+        run: |
+          echo "App ID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}"
+          echo "Project ID: ${{ secrets.FIREBASE_PROJECT_ID }}"
+          echo "FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}"
+          echo "FIREBASE_APP_ID_IOS: ${{ secrets.FIREBASE_APP_ID_IOS }}"
+
+      - name: FIREBASE_TOKEN is # debug test
         run: |
           if [ -z "${{ secrets.FIREBASE_TOKEN }}" ]; then
             echo "FIREBASE_TOKEN is empty"
@@ -112,46 +117,14 @@ jobs:
             echo "FIREBASE_TOKEN starts with: ${FIREBASE_TOKEN:0:5}"
             echo "FIREBASE_TOKEN length: ${#FIREBASE_TOKEN}"
           fi
-
-      # - name: Download Build Artifacts
-      #   uses: actions/download-artifact@v4
-      #   with:
-      #     name: build-artifacts
-      #     path: builds
-
-      # - name: Install Firebase CLI
-      #   run: npm install -g firebase-tools
-
-      # - name: Debug - List Files in Builds Folder
-      #   run: ls -lh builds/
-
-      # - name: Debug - List All Files # debug test
-      #   run: find . -type f
-
-      # - name: Debug - Show Firebase Variables  # debug test
-      #   run: |
-      #     echo "App ID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}"
-      #     echo "Project ID: ${{ secrets.FIREBASE_PROJECT_ID }}"
-      #     echo "FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}"
-      #     echo "FIREBASE_APP_ID_IOS: ${{ secrets.FIREBASE_APP_ID_IOS }}"
-
-      # - name: FIREBASE_TOKEN is
-      #   run: |
-      #     if [ -z "${{ secrets.FIREBASE_TOKEN }}" ]; then
-      #       echo "FIREBASE_TOKEN is empty"
-      #     else
-      #       export FIREBASE_TOKEN="${{ secrets.FIREBASE_TOKEN }}"
-      #       echo "FIREBASE_TOKEN starts with: ${FIREBASE_TOKEN:0:5}"
-      #       echo "FIREBASE_TOKEN length: ${#FIREBASE_TOKEN}"
-      #     fi
         
-      # - name: Upload to Firebase App Distribution (Android)
-      #   run: firebase appdistribution:distribute builds/app-release.apk \
-      #     --app ${{ secrets.FIREBASE_APP_ID_ANDROID }} \
-      #     --groups testers \
-      #     --token ${{ secrets.FIREBASE_TOKEN }} \
-      #     --project ${{ secrets.FIREBASE_PROJECT_ID }} \
-      #     --debug  # Add this for detailed logs
+      - name: Upload to Firebase App Distribution (Android)
+        run: firebase appdistribution:distribute builds/app-release.apk \
+          --app ${{ secrets.FIREBASE_APP_ID_ANDROID }} \
+          --groups testers \
+          --token ${{ secrets.FIREBASE_TOKEN }} \
+          --project ${{ secrets.FIREBASE_PROJECT_ID }} \
+          --debug  # Add this for detailed logs
 
       # - name: Upload to Firebase App Distribution (iOS)
       #   run: firebase appdistribution:distribute builds/*.ipa \
